// ── AHEAD Calculator XLSX Export ─────────────────────────────────────

interface WaterfallStep { n: string; v: number; c: number; }
interface McrResult { py: number; cY: number; wT: number; wI: number; wO: number; wU: number; pA: number; pV: number; sra: number; qD: number; qB: number; eff: number; tA: number; hb: number; fin: number; ffs: number; delta: number; pct: number; wf: WaterfallStep[]; [k: string]: any; }
interface McdResult { py: number; cY: number; wB: number; wI: number; wO: number; sB: number; pT: number; pV: number; sT: number; sdA: number; hA: number; mcS: number; fin: number; ffs: number; delta: number; pct: number; fSh: number; stS: number; wf: WaterfallStep[]; [k: string]: any; }
interface McYearResult { py: number; cY: number; cp10: number; cp25: number; cp50: number; cp75: number; cp90: number; cffs: number; pA: number; spread: number; var5: number; cvar5: number; rho: number; [k: string]: any; }
interface SensItem { nm: string; lo: number; hi: number; p: string; }
interface HospInfo { nm: string; st: string; beds: number; ty: string; co: number; wi: number; cdi: number; hcc: number; }

export async function generateAheadXlsx(input: {
  hospital: HospInfo;
  mr: McrResult;
  dr: McdResult;
  mp: McrResult[];
  dp: McdResult[];
  mc: McYearResult[];
  sens: SensItem[];
}): Promise<void> {
  const XLSX = await import("xlsx");
  const { hospital, mr, dr, mp, dp, mc, sens } = input;
  const wb = XLSX.utils.book_new();

  // ── Hospital Info sheet ──
  const hospData = [
    ["Hospital", hospital.nm],
    ["State", hospital.st],
    ["Beds", hospital.beds],
    ["Type", hospital.ty],
    ["Cohort", hospital.co],
    ["Wage Index", hospital.wi],
    ["CDI", hospital.cdi],
    ["HCC Score", hospital.hcc],
    ["", ""],
    ["Generated by Aradune", new Date().toISOString().split("T")[0]],
  ];
  const wsHosp = XLSX.utils.aoa_to_sheet(hospData);
  wsHosp["!cols"] = [{ wch: 18 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, wsHosp, "Hospital Info");

  // ── Medicare HGB sheet ──
  const mcrData = [
    ["Medicare HGB Results"],
    [""],
    ["Metric", "Value"],
    ["Performance Year", mr.py],
    ["Calendar Year", mr.cY],
    ["Weighted Base Total", mr.wT],
    ["Weighted IP", mr.wI],
    ["Weighted OP", mr.wO],
    ["Weighted UC", mr.wU],
    ["APA-Adjusted Total", mr.pA],
    ["Volume-Adjusted Total", mr.pV],
    ["Safety Risk Adj", mr.sra],
    ["Quality Delta", mr.qD],
    ["Quality Bonus Factor", mr.qB],
    ["Efficiency Adj", mr.eff],
    ["TCOC Adj", mr.tA],
    ["Health Equity Bonus", mr.hb],
    ["HGB Final", mr.fin],
    ["FFS Counterfactual", mr.ffs],
    ["Delta", mr.delta],
    ["% Change", mr.pct],
    [""],
    ["Waterfall"],
    ["Step", "Amount", "Cumulative"],
    ...mr.wf.map((s: WaterfallStep) => [s.n, s.v, s.c]),
  ];
  const wsMcr = XLSX.utils.aoa_to_sheet(mcrData);
  wsMcr["!cols"] = [{ wch: 24 }, { wch: 18 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(wb, wsMcr, "Medicare HGB");

  // ── Medicaid HGB sheet ──
  const mcdData = [
    ["Medicaid HGB Results"],
    [""],
    ["Metric", "Value"],
    ["Performance Year", dr.py],
    ["Calendar Year", dr.cY],
    ["Weighted Base", dr.wB],
    ["Weighted IP", dr.wI],
    ["Weighted OP", dr.wO],
    ["Supplemental Base", dr.sB],
    ["Trended Payment", dr.pT],
    ["Volume-Adjusted Payment", dr.pV],
    ["Supplemental Trended", dr.sT],
    ["SDOH Adjustment", dr.sdA],
    ["HEDIS Adjustment", dr.hA],
    ["Managed Care Savings", dr.mcS],
    ["HGB Final", dr.fin],
    ["FFS Counterfactual", dr.ffs],
    ["Delta", dr.delta],
    ["% Change", dr.pct],
    ["Federal Share", dr.fSh],
    ["State Share", dr.stS],
    [""],
    ["Waterfall"],
    ["Step", "Amount", "Cumulative"],
    ...dr.wf.map((s: WaterfallStep) => [s.n, s.v, s.c]),
  ];
  const wsMcd = XLSX.utils.aoa_to_sheet(mcdData);
  wsMcd["!cols"] = [{ wch: 24 }, { wch: 18 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(wb, wsMcd, "Medicaid HGB");

  // ── Projections sheet ──
  const projData = [
    ["Multi-Year Projections"],
    [""],
    ["Year", "MCR HGB", "MCR FFS", "MCR Delta", "MCD HGB", "MCD FFS", "MCD Delta", "Combined HGB", "Combined FFS", "Combined Delta"],
    ...mp.map((r, i) => [
      `PY${r.py}`,
      r.fin, r.ffs, r.delta,
      dp[i].fin, dp[i].ffs, dp[i].delta,
      r.fin + dp[i].fin, r.ffs + dp[i].ffs,
      (r.fin + dp[i].fin) - (r.ffs + dp[i].ffs),
    ]),
    [""],
    ["Monte Carlo Summary"],
    ["Year", "P10", "P25", "P50 (Median)", "P75", "P90", "FFS Baseline", "Δ Median", "P(AHEAD > FFS)", "Spread", "VaR 5%", "CVaR 5%", "ρ(MCR,MCD)"],
    ...mc.map(r => [
      `PY${r.py}`,
      r.cp10, r.cp25, r.cp50, r.cp75, r.cp90,
      r.cffs, r.cp50 - r.cffs,
      r.pA, r.spread, r.var5, r.cvar5, r.rho,
    ]),
  ];
  const wsProj = XLSX.utils.aoa_to_sheet(projData);
  wsProj["!cols"] = Array(13).fill({ wch: 16 });
  XLSX.utils.book_append_sheet(wb, wsProj, "Projections");

  // ── Sensitivity sheet ──
  const sensData = [
    ["Sensitivity Analysis"],
    [""],
    ["Variable", "Program", "Low Impact", "High Impact", "Range"],
    ...sens.map(s => [s.nm, s.p, s.lo, s.hi, Math.abs(s.hi - s.lo)]),
  ];
  const wsSens = XLSX.utils.aoa_to_sheet(sensData);
  wsSens["!cols"] = [{ wch: 16 }, { wch: 10 }, { wch: 16 }, { wch: 16 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, wsSens, "Sensitivity");

  XLSX.writeFile(wb, `ahead_export_${hospital.nm.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.xlsx`);
}
