// ── Shared PDF Report Utilities ──────────────────────────────────────
// Uses dynamic import so jspdf only loads when a pro user triggers export.

import type jsPDF from "jspdf";

// Brand colors as RGB arrays for jsPDF
const BRAND: [number, number, number] = [46, 107, 74];   // C.brand #2E6B4A
const INK: [number, number, number] = [10, 37, 64];       // C.ink #0A2540
const INK_LIGHT: [number, number, number] = [66, 90, 112]; // C.inkLight #425A70

export async function loadJsPDF(): Promise<typeof import("jspdf")> {
  return import("jspdf");
}

export async function loadAutoTable(): Promise<typeof import("jspdf-autotable")> {
  return import("jspdf-autotable");
}

export async function createAradunePDF(title: string): Promise<jsPDF> {
  const { default: jsPDF } = await loadJsPDF();
  await loadAutoTable(); // registers the autoTable plugin

  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });

  // Header bar
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, 612, 44, "F");

  // "ARADUNE" wordmark
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text("ARADUNE", 28, 28);

  // Date right-aligned
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), 584, 28, { align: "right" });

  // Report title
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 28, 72);

  return doc;
}

export function addSection(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(...BRAND);
  doc.rect(28, y, 4, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...BRAND);
  doc.text(title, 38, y + 11);
  return y + 22;
}

export function addFooter(doc: jsPDF, sources: string[]): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(200, 200, 200);
    doc.line(28, 752, 584, 752);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...INK_LIGHT);
    doc.text(`Generated by Aradune | aradune.co`, 28, 764);
    doc.text(`Page ${i} of ${pageCount}`, 584, 764, { align: "right" });
    if (sources.length > 0) {
      doc.text(`Sources: ${sources.join(" · ")}`, 28, 774);
    }
  }
}

export function formatCurrency(v: number): string {
  return "$" + v.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function formatPercent(v: number): string {
  return (v >= 0 ? "+" : "") + (v * 100).toFixed(2) + "%";
}

export function formatPct1(v: number): string {
  return (v >= 0 ? "+" : "") + v.toFixed(1) + "%";
}

export { BRAND, INK, INK_LIGHT };
