// ── Rate Builder XLSX Export ─────────────────────────────────────────
import type { RateComponent } from "../types";

interface StateRate { st: string; rate: number; name: string; }

interface RateBuilderXlsxInput {
  code: string;
  desc: string | null;
  medicareRate: number | null;
  methodology: string;
  formula: string;
  components: RateComponent[];
  rate: number;
  stateRates: StateRate[];
  nStates: number;
}

export async function generateRateBuilderXlsx(input: RateBuilderXlsxInput): Promise<void> {
  const XLSX = await import("xlsx");
  const { code, desc, medicareRate, methodology, formula, components, rate, stateRates, nStates } = input;
  const wb = XLSX.utils.book_new();

  // ── Summary sheet ──
  const summaryData = [
    ["HCPCS Code", code],
    ["Description", desc || ""],
    ["Methodology", methodology],
    ["Formula", formula],
    ["Calculated Rate", rate],
    ["Medicare CY2025 Rate", medicareRate || "N/A"],
    ["% of Medicare", medicareRate ? +(rate / medicareRate * 100).toFixed(1) : "N/A"],
    ["States with T-MSIS Data", nStates],
    ["", ""],
    ["Generated by Aradune", new Date().toISOString().split("T")[0]],
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  wsSummary["!cols"] = [{ wch: 22 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

  // ── Components sheet ──
  const compData = [["Component", "Value", "Note"]];
  components.forEach((c: RateComponent) => {
    compData.push([c.label, c.value, c.note || ""]);
  });
  const wsComp = XLSX.utils.aoa_to_sheet(compData);
  wsComp["!cols"] = [{ wch: 24 }, { wch: 16 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, wsComp, "Components");

  // ── State Comparison sheet ──
  if (stateRates.length > 0) {
    const stateData = [["State", "T-MSIS Rate", "Calculated Rate", "Change ($)", "Change (%)"]];
    stateRates.forEach(s => {
      const diff = rate - s.rate;
      const pctChg = ((rate / s.rate) - 1) * 100;
      stateData.push([
        s.name,
        +s.rate.toFixed(2) as any,
        +rate.toFixed(2) as any,
        +diff.toFixed(2) as any,
        +pctChg.toFixed(1) as any,
      ]);
    });
    const wsState = XLSX.utils.aoa_to_sheet(stateData);
    wsState["!cols"] = [{ wch: 16 }, { wch: 14 }, { wch: 16 }, { wch: 14 }, { wch: 14 }];
    XLSX.utils.book_append_sheet(wb, wsState, "State Comparison");
  }

  XLSX.writeFile(wb, `rate_export_${code}_${new Date().toISOString().split("T")[0]}.xlsx`);
}
