/**
 * Excel Report Export
 * Generates a multi-sheet Excel workbook from accumulated report sections.
 * Sheet 1: Overview (all sections with prompts + summary)
 * Sheet 2+: One sheet per section that contains a markdown table.
 */

import { extractAllTables } from "./reportMarkdown";

interface ReportSection {
  id: string;
  prompt: string;
  response: string;
  queries: string[];
  createdAt: Date;
}

export async function generateReportXlsx(
  sections: ReportSection[],
  title?: string
): Promise<void> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  const date = new Date().toISOString().split("T")[0];
  const reportTitle = title || "Medicaid Intelligence Report";

  // ── Overview sheet ────────────────────────────────────────────────────

  const overviewData: (string | number)[][] = [
    [reportTitle],
    [`Generated: ${date}`],
    [`Sections: ${sections.length}`],
    [],
    ["#", "Prompt", "Response (first 500 chars)", "Tables", "Queries", "Timestamp"],
  ];

  sections.forEach((section, idx) => {
    const tables = extractAllTables(section.response);
    const d = section.createdAt instanceof Date
      ? section.createdAt
      : new Date(section.createdAt);
    overviewData.push([
      idx + 1,
      section.prompt,
      section.response.slice(0, 500).replace(/\n/g, " "),
      tables.length,
      (section.queries || []).length,
      d.toLocaleString("en-US"),
    ]);
  });

  const wsOverview = XLSX.utils.aoa_to_sheet(overviewData);
  wsOverview["!cols"] = [
    { wch: 4 },
    { wch: 50 },
    { wch: 80 },
    { wch: 8 },
    { wch: 8 },
    { wch: 20 },
  ];
  XLSX.utils.book_append_sheet(wb, wsOverview, "Overview");

  // ── Per-section table sheets ──────────────────────────────────────────

  let tableSheetCount = 0;
  sections.forEach((section, sIdx) => {
    const tables = extractAllTables(section.response);
    tables.forEach((table, tIdx) => {
      tableSheetCount++;
      const sheetData: (string | number)[][] = [
        [`Section ${sIdx + 1}${tables.length > 1 ? `, Table ${tIdx + 1}` : ""}`],
        [section.prompt],
        [],
        table.columns,
        ...table.rows,
      ];

      const ws = XLSX.utils.aoa_to_sheet(sheetData);
      // Auto-size columns based on header length
      ws["!cols"] = table.columns.map((col) => ({
        wch: Math.max(col.length + 2, 12),
      }));

      // Sheet name must be unique and ≤31 chars
      const sheetName = `S${sIdx + 1}${tables.length > 1 ? `-T${tIdx + 1}` : ""} Data`;
      XLSX.utils.book_append_sheet(wb, ws, sheetName.slice(0, 31));
    });
  });

  // ── Queries sheet ─────────────────────────────────────────────────────

  const allQueries = sections.flatMap((s, idx) =>
    (s.queries || []).map((q) => [idx + 1, q])
  );
  if (allQueries.length > 0) {
    const queryData: (string | number)[][] = [
      ["SQL Queries Executed"],
      [],
      ["Section", "Query"],
      ...allQueries,
    ];
    const wsQueries = XLSX.utils.aoa_to_sheet(queryData);
    wsQueries["!cols"] = [{ wch: 10 }, { wch: 120 }];
    XLSX.utils.book_append_sheet(wb, wsQueries, "Queries");
  }

  // ── Notes sheet ───────────────────────────────────────────────────────

  const notesData: (string | number)[][] = [
    ["Report Notes"],
    [],
    ["Generated by", "Aradune | aradune.co"],
    ["Date", date],
    ["Sections", sections.length],
    ["Data tables extracted", tableSheetCount],
    [],
    ["Data sourced from the Aradune Medicaid Data Lake"],
    ["669 fact tables, 400M+ rows of public Medicaid data"],
  ];
  const wsNotes = XLSX.utils.aoa_to_sheet(notesData);
  wsNotes["!cols"] = [{ wch: 28 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, wsNotes, "Notes");

  XLSX.writeFile(wb, `aradune-report-${date}.xlsx`);
}
