"""
Read entity/domain/metrics YAML files and generate:
1. Intelligence system prompt section (ontology/generated_prompt.md)
2. DuckPGQ property graph SQL (sql/property_graph.sql)
3. Validation report (stdout)

Usage: python3 scripts/generate_ontology.py
"""
import yaml
from pathlib import Path

ROOT = Path(__file__).parent.parent
ONTOLOGY = ROOT / "ontology"
PROMPT_OUT = ONTOLOGY / "generated_prompt.md"
GRAPH_OUT = ROOT / "sql" / "property_graph.sql"


def load_yaml_dir(subdir):
    result = {}
    d = ONTOLOGY / subdir
    if not d.exists():
        return result
    for f in sorted(d.glob("*.yaml")):
        with open(f) as fh:
            data = yaml.safe_load(fh)
        key = data.get("entity") or data.get("domain") or f.stem
        result[key] = data
    return result


def generate_prompt(entities, domains, metrics):
    """Generate the auto-generated data section of the Intelligence system prompt."""
    lines = ["## The Aradune Data Lake\n"]

    for domain_name, domain in sorted(domains.items(), key=lambda x: x[1].get("display_name", "")):
        lines.append(f"### {domain['display_name']}")
        lines.append(f"{domain.get('description', '')}\n")

        for t in domain.get("primary_tables", []):
            table = t["table"]
            rows = t.get("row_count", "?")
            if isinstance(rows, int):
                rows = f"{rows:,}"
            lines.append(f"- **{table}**: {rows} rows")

        supporting = domain.get("supporting_tables", [])
        if supporting:
            names = ", ".join(supporting[:10])
            if len(supporting) > 10:
                names += f" (+{len(supporting) - 10} more)"
            lines.append(f"- Supporting: {names}")

        # Planned tables (not yet ingested but known)
        planned = domain.get("planned_tables", [])
        if planned:
            lines.append("\n**Planned (not yet in lake):**")
            for p in planned:
                lines.append(f"- {p['table']}: {p.get('description', '')}")

        # Metrics for this domain
        domain_metrics = metrics.get(domain_name, {}).get("metrics", [])
        # Also check by file name pattern
        for mk, mv in metrics.items():
            if mv.get("domain") == domain_name and domain_name not in mk:
                domain_metrics.extend(mv.get("metrics", []))

        if domain_metrics:
            lines.append("\n**Named metrics (use these for consistency):**")
            seen = set()
            for m in domain_metrics:
                if m["name"] in seen:
                    continue
                seen.add(m["name"])
                desc = m.get("description", "")
                formula = m.get("formula", "")
                line = f"- `{m['name']}`: {desc}"
                if formula:
                    line += f" = `{formula}`"
                lines.append(line)

        lines.append("")

    # Entity relationships section
    lines.append("## How entities connect\n")
    for entity_name, entity in sorted(entities.items()):
        ft = entity.get("fact_tables", [])
        if ft:
            pk = entity.get("primary_key", "?")
            ct = entity.get("canonical_table", "?")
            display = entity.get("display_name", entity_name)
            lines.append(f"**{display}** (`{ct}`, key: `{pk}`): {len(ft)} fact tables")

    lines.append("")

    # Join keys
    lines.append("## Universal join keys\n")
    lines.append("- `state_code` (VARCHAR 2): links most tables to dim_state")
    lines.append("- `cpt_hcpcs_code` / `procedure_code`: links to dim_procedure (RVUs, descriptions)")
    lines.append("- `provider_ccn` / `ccn`: links hospital tables to HCRIS/quality data")
    lines.append("- `npi`: links provider-level tables")
    lines.append("- `ndc`: links drug/pharmacy tables")
    lines.append("- `soc_code`: links workforce/occupation tables to dim_bls_occupation")
    lines.append("- `county_fips` / `fips_code`: links geographic/county-level data")
    lines.append("- `measure_id`: links quality measure tables to dim_scorecard_measure")
    lines.append("")

    return "\n".join(lines)


def generate_duckpgq(entities):
    """Generate CREATE PROPERTY GRAPH SQL from entity registry."""
    # Only entities with actual canonical tables that are dimension/reference
    vertex_candidates = {}
    for ename, entity in entities.items():
        ct = entity.get("canonical_table", "")
        pk = entity.get("primary_key", "")
        if ct.startswith("dim_") and pk:
            vertex_candidates[ename] = (ct, pk)

    if not vertex_candidates:
        return "-- No dimension tables found for DuckPGQ vertex tables\n"

    lines = [
        "-- Auto-generated by scripts/generate_ontology.py",
        "-- DuckPGQ property graph over the Aradune data lake",
        "",
        "INSTALL duckpgq FROM community;",
        "LOAD duckpgq;",
        "",
        "CREATE OR REPLACE PROPERTY GRAPH medicaid",
        "VERTEX TABLES (",
    ]

    vertex_lines = []
    for ename, (ct, pk) in sorted(vertex_candidates.items()):
        vertex_lines.append(f"    {ct} (LABEL {ename})")
    lines.append(",\n".join(vertex_lines))
    lines.append(")")

    # Edge tables: fact tables that connect two vertex entities
    edge_lines = []
    seen = set()
    for ename, entity in entities.items():
        if ename not in vertex_candidates:
            continue
        ct_source, pk_source = vertex_candidates[ename]
        for ft in entity.get("fact_tables", []):
            # Check if this fact table also connects to another vertex entity
            for other_name, (ct_dest, pk_dest) in vertex_candidates.items():
                if other_name == ename:
                    continue
                # This would require checking if the fact table has both keys
                # For now, generate edges for state → procedure via rate tables
                edge_key = (ft, ename, other_name)
                if edge_key in seen:
                    continue
                # Only create well-known edges
                if ename == "state" and other_name == "procedure" and "rate" in ft:
                    seen.add(edge_key)
                    label = f"{ename}_to_{other_name}"
                    edge_lines.append(
                        f"    {ft}\n"
                        f"        SOURCE KEY ({pk_source}) REFERENCES {ct_source} ({pk_source})\n"
                        f"        DESTINATION KEY ({pk_dest}) REFERENCES {ct_dest} ({pk_dest})\n"
                        f"        LABEL {label}"
                    )

    if edge_lines:
        lines.append("EDGE TABLES (")
        lines.append(",\n".join(edge_lines))
        lines.append(")")

    lines.append(";")
    return "\n".join(lines)


def main():
    print("Loading ontology YAML...")
    entities = load_yaml_dir("entities")
    domains = load_yaml_dir("domains")
    metrics_raw = load_yaml_dir("metrics")

    # Re-key metrics by domain name
    metrics = {}
    for k, v in metrics_raw.items():
        domain = v.get("domain", k)
        metrics[domain] = v

    print(f"  {len(entities)} entities, {len(domains)} domains, {len(metrics)} metric files\n")

    # Generate prompt
    print("Generating Intelligence system prompt section...")
    prompt = generate_prompt(entities, domains, metrics)
    PROMPT_OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(PROMPT_OUT, "w") as f:
        f.write(prompt)
    print(f"  Written to {PROMPT_OUT} ({len(prompt):,} chars)\n")

    # Generate DuckPGQ
    print("Generating DuckPGQ property graph SQL...")
    sql = generate_duckpgq(entities)
    GRAPH_OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(GRAPH_OUT, "w") as f:
        f.write(sql)
    print(f"  Written to {GRAPH_OUT}\n")

    # Summary stats
    total_tables = 0
    total_rows = 0
    for d in domains.values():
        for t in d.get("primary_tables", []):
            total_tables += 1
            total_rows += t.get("row_count", 0)
        total_tables += len(d.get("supporting_tables", []))

    total_metrics = sum(len(m.get("metrics", [])) for m in metrics.values())
    total_fact_refs = sum(len(e.get("fact_tables", [])) for e in entities.values())

    print(f"Summary:")
    print(f"  {len(entities)} entities with {total_fact_refs} fact table references")
    print(f"  {len(domains)} domains covering {total_tables} tables ({total_rows:,} rows)")
    print(f"  {total_metrics} named metrics")
    print(f"  Prompt: {len(prompt):,} chars")


if __name__ == "__main__":
    main()
