-- Auto-generated by scripts/generate_ontology.py
-- DuckPGQ property graph over the Aradune data lake

INSTALL duckpgq FROM community;
LOAD duckpgq;

CREATE OR REPLACE PROPERTY GRAPH medicaid
VERTEX TABLES (
    dim_bls_occupation (LABEL occupation),
    dim_procedure (LABEL procedure),
    dim_scorecard_measure (LABEL quality_measure),
    dim_state (LABEL state)
)
EDGE TABLES (
    fact_chip_unwinding_separate
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_integrated_care
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_medicaid_rate
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_medicare_rate
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_medicare_rate_state
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_nas_rates
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_property_tax_rate
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_rate_comparison
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure,
    fact_state_tax_rates
        SOURCE KEY (state_code) REFERENCES dim_state (state_code)
        DESTINATION KEY (cpt_hcpcs_code) REFERENCES dim_procedure (cpt_hcpcs_code)
        LABEL state_to_procedure
)
;